import { Asset } from './types';

export const ASSETS: Asset[] = [
  {
    rank: 1,
    letter: 'P',
    name: 'PENGUIN',
    category: 'Digital Asset',
    price: '$28.9258',
    change: '4.90%',
    isPositive: false,
  },
  {
    rank: 2,
    letter: 'S',
    name: 'SKR',
    category: 'Digital Asset',
    price: '$9.6030',
    change: '13.83%',
    isPositive: true,
  },
  {
    rank: 3,
    letter: 'F',
    name: 'FARTCOIN',
    category: 'Digital Asset',
    price: '$8.9534',
    change: '10.64%',
    isPositive: true,
  },
  {
    rank: 4,
    letter: 'S',
    name: 'SOLANA',
    category: 'Digital Asset',
    price: '$62.7877',
    change: '15.33%',
    isPositive: false,
  },
  {
    rank: 5,
    letter: 'J',
    name: 'JUPITER',
    category: 'Digital Asset',
    price: '$48.6961',
    change: '12.06%',
    isPositive: true,
  },
  {
    rank: 6,
    letter: 'P',
    name: 'PYTH',
    category: 'Digital Asset',
    price: '$75.1711',
    change: '16.46%',
    isPositive: false,
  },
  {
    rank: 7,
    letter: 'R',
    name: 'RAYDIUM',
    category: 'Digital Asset',
    price: '$22.0928',
    change: '7.53%',
    isPositive: true,
  },
  {
    rank: 8,
    letter: 'B',
    name: 'BONK',
    category: 'Digital Asset',
    price: '$19.3443',
    change: '12.53%',
    isPositive: true,
  },
  {
    rank: 9,
    letter: 'O',
    name: 'ORCA',
    category: 'Digital Asset',
    price: '$4.3866',
    change: '2.65%',
    isPositive: true,
  },
  {
    rank: 10,
    letter: 'W',
    name: 'WIF',
    category: 'Digital Asset',
    price: '$3.4567',
    change: '8.45%',
    isPositive: true,
  },
  {
    rank: 11,
    letter: 'M',
    name: 'MOG',
    category: 'Digital Asset',
    price: '$1.2345',
    change: '5.67%',
    isPositive: false,
  },
  {
    rank: 12,
    letter: 'P',
    name: 'POPCAT',
    category: 'Digital Asset',
    price: '$0.9876',
    change: '12.34%',
    isPositive: true,
  },
  {
    rank: 13,
    letter: 'B',
    name: 'BODEN',
    category: 'Digital Asset',
    price: '$0.5432',
    change: '23.45%',
    isPositive: false,
  },
  {
    rank: 14,
    letter: 'T',
    name: 'TRUMP',
    category: 'Digital Asset',
    price: '$7.8901',
    change: '1.23%',
    isPositive: true,
  },
  {
    rank: 15,
    letter: 'S',
    name: 'SLERF',
    category: 'Digital Asset',
    price: '$0.6789',
    change: '9.87%',
    isPositive: false,
  },
  {
    rank: 16,
    letter: 'M',
    name: 'MEW',
    category: 'Digital Asset',
    price: '$0.0056',
    change: '6.54%',
    isPositive: true,
  },
  {
    rank: 17,
    letter: 'W',
    name: 'WEN',
    category: 'Digital Asset',
    price: '$0.0002',
    change: '3.21%',
    isPositive: false,
  },
  {
    rank: 18,
    letter: 'G',
    name: 'GIGA',
    category: 'Digital Asset',
    price: '$0.0345',
    change: '15.67%',
    isPositive: true,
  },
  {
    rank: 19,
    letter: 'K',
    name: 'KEYCAT',
    category: 'Digital Asset',
    price: '$0.0678',
    change: '4.32%',
    isPositive: false,
  },
  {
    rank: 20,
    letter: 'T',
    name: 'TOOKER',
    category: 'Digital Asset',
    price: '$0.0123',
    change: '7.89%',
    isPositive: true,
  },
];

export const SIGNAL_ASSETS: Asset[] = [
  { rank: 1, letter: 'B', name: 'BITCOIN', category: 'Momentum', price: '$94,281', change: '2.14%', isPositive: true },
  { rank: 2, letter: 'E', name: 'ETHEREUM', category: 'Momentum', price: '$3,104', change: '1.82%', isPositive: true },
  { rank: 3, letter: 'S', name: 'SOLANA', category: 'Breakout', price: '$242.15', change: '5.92%', isPositive: true },
  { rank: 4, letter: 'X', name: 'XRP', category: 'Volatility', price: '$1.04', change: '12.45%', isPositive: true },
  { rank: 5, letter: 'A', name: 'AVALANCHE', category: 'Consolidation', price: '$34.82', change: '0.45%', isPositive: false },
  { rank: 6, letter: 'D', name: 'DOGE', category: 'Meme Wave', price: '$0.3842', change: '8.21%', isPositive: true },
  { rank: 7, letter: 'C', name: 'CARDANO', category: 'Stability', price: '$0.7214', change: '1.45%', isPositive: true },
  { rank: 8, letter: 'P', name: 'POLKADOT', category: 'Ecosystem', price: '$7.8421', change: '4.32%', isPositive: false },
  { rank: 9, letter: 'L', name: 'LITECOIN', category: 'Legacy', price: '$88.24', change: '2.11%', isPositive: true },
  { rank: 10, letter: 'N', name: 'NEAR', category: 'Growth', price: '$5.62', change: '7.82%', isPositive: true },
  { rank: 11, letter: 'F', name: 'FANTOM', category: 'Scalability', price: '$0.92', change: '15.42%', isPositive: true },
  { rank: 12, letter: 'I', name: 'INJECTIVE', category: 'DeFi Hub', price: '$24.52', change: '3.21%', isPositive: false },
  { rank: 13, letter: 'T', name: 'THE GRAPH', category: 'Indexing', price: '$0.28', change: '9.45%', isPositive: true },
  { rank: 14, letter: 'S', name: 'SUI', category: 'L1 Trend', price: '$3.42', change: '6.78%', isPositive: true },
  { rank: 15, letter: 'A', name: 'APTOS', category: 'Move Ecosystem', price: '$12.14', change: '4.21%', isPositive: false },
];
